spring:
  application:
    name: mc-notification
  datasource:
    url: jdbc:postgresql://localhost:5432/mcnotification
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: create

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopic: "notification-topic"
    kafkaMessageGroupId: "kafka-message-group-id"


