server:
  port: 8089
  servlet:
    context-path: /app

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/mcnotification
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: create

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  kafka:
    bootstrap-servers: localhost:9092


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      register-with-eureka: true
      fetch-registry: true
  instance:
    hostname: localhost


app:
  kafka:
    kafkaMessageTopic: "notification-topic"
    kafkaMessageGroupId: "kafka-message-group-id"

#jwt:
#  secret: "ihuhijhgdrftgyhujikopooiuh"


auth:
  service:
    url: http://localhost:8086

friend:
  service:
    url: http://localhost:8090

