spring:
  application:
    name: mc-notification
  datasource:
    url: jdbc:postgresql://localhost:5435/mc_not
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopic: "notification-topic"
    kafkaMessageGroupId: "notification-topic-0"

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
